import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
import { cn } from "@/lib/utils";
import LayoutComponent from "@/layouts/layout";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased ",
          inter.variable
        )}
      >
        <LayoutComponent>{children}</LayoutComponent>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
